version: "3.5"

services:

  tron-client:
    image: tron
    container_name: tron
    hostname: tron
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/:/opt/graphsense/data:Z
      - ./conf/main_net_config.conf:/opt/graphsense/client2.conf:Z
      - ./logs/:/home/dockeruser/logs:Z
    ports:
      - 50545:50545
      - 50555:50555
      - 50051:50051
      - 58090:8090
      - 58091:8091
    networks:
      - graphsense-net
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1024m"

networks:
  graphsense-net:
    name: graphsense-global-net
